ESP_32/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('Noise_Pollution/', include('Noise_Pollution.urls')),
    path('admin/', admin.site.urls),
]

Noise_Pollution/urls.py

from django.urls import path
from . import views

app_name = 'Noise_Pollution'
urlpatterns = [
    path('', views.index, name='index'),
    path('sensor_list/', views.sensors, name='sensors'),
    path('<int:id>/', views.chart, name='chart'),
    path('send_data/<int:id>/', views.send_data, name='send_data'),
    path('add_sensor/', views.add_sensor, name='add_sensor'),
    path('room_list/', views.rooms, name='rooms'),
    path('manage_sensors/', views.manage_sensors, name='manage_sensors'),
    path('room/<int:id>/', views.room_sensors, name='room_sensors'),
    path('change_time_collection/<int:id>/', views.change_time_collection, name="change_time_collection"),
    path('move_sensor/<int:id>/', views.move_sensor, name='move_sensor'),
    path('delete_sensor/<int:id>/', views.delete_sensor, name='delete_sensor'),
    path('delete_room/<int:id>/', views.delete_room, name='delete_room'),
    path('add_room/', views.add_room, name='add_room'),
    path('<int:id>/chart_data/', views.ChartData.as_view(), name='chart_data'),
    path('<int:id>/history_one_day/<str:data>', views.history_chart, name='history_one_day'),
    path('<int:id>/history_more_days/<str:datastart>/<str:dataend>', views.history_chart2, name='history_one_day2')
    ]

Noise_Pollution/models.py
from django.db import models
# Create your models here.


class Stanza(models.Model):
    name = models.CharField(max_length=20)
    rep = models.CharField(max_length=50)
    mail = models.EmailField()

    def __str__(self):
        return self.name


class Sensore(models.Model):
    id = models.IntegerField(primary_key=True)
    type = models.BooleanField()  # 0 digitale, 1 analogico
    room = models.ForeignKey(Stanza, on_delete=models.CASCADE, default="")
    key = models.CharField(max_length=15, default='000000000000000')
    authenticated = models.BooleanField(default=0)
    time_collection = models.IntegerField(default=0)

    def is_analogic(self):
        return self.type


class Dati(models.Model):
    sensore = models.ForeignKey(Sensore, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    analogic_value = models.IntegerField(default=-1)
    digital_value = models.BooleanField(null=True)






Noise_Pollution/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from .models import Sensore, Dati, Stanza
from .form import NewSensor, MoveSensor, NewRoom, SetSensorTime, Filter
from .functions import random_password
from django.shortcuts import redirect
from datetime import datetime
from rest_framework.views import APIView
from rest_framework.response import Response

from requests import get
import json

max_threshold = 70


def index(request):
    return render(request, 'Noise_Pollution/index.html', {})


def sensors(request):
    sensori_list = Sensore.objects.order_by('id')
    if request.method == "POST":
        form = Filter(request.POST)
        sens_type = request.POST['sensorType']
        sens_room = request.POST['room']
        if sens_type == '0' or sens_type == '1':
            t = sens_type == '1'
            if sens_room is not '':
                sensori_list = Sensore.objects.filter(type=t, room=sens_room)
            else:
                sensori_list = Sensore.objects.filter(type=t)
        else:
            if sens_room is not '':
                sensori_list = Sensore.objects.filter(room=sens_room)
    else:
        form = Filter()
    active = dict()
    for sens in list(sensori_list):
        try:
            data = Dati.objects.filter(sensore=sens.id).latest('date', 'time')
            if data.date == datetime.now().date() and datetime.now().time().hour == data.time.hour and datetime.now().time().minute == data.time.minute and datetime.now().time().second-10 <= data.time.second:
                active[sens.id] = 1
            else:
                active[sens.id] = 0
        except ObjectDoesNotExist:
            active[sens.id] = -1

    context = {
        'sensori_list': sensori_list,
        'current_time': datetime.now().time(),
        'current_data': datetime.now().date(),
        'active': active,
        'form': form
        }
    return render(request, 'Noise_Pollution/sensors.html', context)


def manage_sensors(request):
    form = SetSensorTime()
    sensori_list = Sensore.objects.order_by('id')
    context = {
        'sensori_list': sensori_list,
        'form': form
    }
    return render(request, 'Noise_Pollution/manage_sensors.html', context)


def rooms(request):
    sensori_list = Sensore.objects.order_by('id')
    stanza_list = list(Stanza.objects.order_by('id'))
    state = dict()
    for room in stanza_list:
        state[room.id] = 0
        try:
            sensor = Sensore.objects.get(room=room.id)
        except ObjectDoesNotExist:                                      # no sensors
            state[room.id] = -1
            continue

        except MultipleObjectsReturned:                                 # multiple sensors
            for obj in Sensore.objects.filter(room=room.id):
                latest_data = list(Dati.objects.filter(sensore=obj.id))[-20:]
                if state[room.id] == 0:
                    for data in latest_data:
                        if obj.type:   # analogical sensor
                            if data.analogic_value > max_threshold:
                                state[room.id] = 1
                        else:          # digital sensor
                            state[room.id] = 1 if data.digital_value else 0
            continue

        latest_data = list(Dati.objects.filter(sensore=sensor.id))[-20:]      # single sensor
        for data in latest_data:
            if sensor.type:
                if data.analogic_value > max_threshold:
                    state[room.id] = 1
                else:
                    state[room.id] = 1 if data.digital_value else 0
    return render(request, 'Noise_Pollution/rooms.html', {'stanza_list': stanza_list, 'sensori_list': sensori_list, 'room_state': state})


def room_sensors(request, id):
    sensors_list = Sensore.objects.filter(room=id)
    room = Stanza.objects.get(id=id)
    return render(request, 'Noise_Pollution/room_sensors.html', {'sensori_list': sensors_list, 'room': room})


def chart(request, id):
    dati_list = list(Dati.objects.filter(sensore=id))[-30:]
    return render(request, 'Noise_Pollution/chart.html', {'dati_list': dati_list, 'id': id})


class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, id):
        labels = []
        dati = []
        for obj in list(Dati.objects.filter(sensore=id))[-30:]:
            date = str(obj.time.hour)+':'+str(obj.time.minute)+':'+str(obj.time.second)
            labels.append(date)
            if obj.sensore.type:
                dati.append(obj.analogic_value)
            else:
                dati.append(obj.digital_value)
        data = {
            "labels": labels,
            "dati": dati
        }
        return Response(data)


@csrf_exempt
def send_data(request, id):
    try:
        sensor = Sensore.objects.get(id=id)
    except ObjectDoesNotExist:
        print("Sensor "+id+" doesn't exist")
        return HttpResponse("Sensor "+id+" doesn't exist")

    if request.method == "POST":
        threshold_exceeded = False
        json_data = json.loads(request.body.decode("utf-8"))
        if sensor.key != json_data['key']:
            print("ACCESS DENIED!")
            return HttpResponse("ACCESS DENIED!")
        if not sensor.authenticated:
            sensor.authenticated = 1
        value = int(float(json_data['value']))
        if sensor.is_analogic():
            if value > 1:
                Dati.objects.create(
                                        sensore=sensor,
                                        analogic_value=value
                                    )
                threshold_exceeded = value > max_threshold
            else:
                print("Wrong sensor type")
                HttpResponse("Wrong sensor type")

        else:
            if value == (1 or 0):
                Dati.objects.create(
                                        sensore=sensor,
                                        digital_value=json_data['value']
                                    )
                threshold_exceeded = value == 1
            else:
                print("Wrong sensor type")
                HttpResponse("Wrong sensor type")
        print("Data collected.")

        if threshold_exceeded:  # send an e-mail
            email = sensor.room.mail
            message = "The maximum threshold is exceeded in "+sensor.location+". Please, talk less loudly."
            get('http://ame97software.altervista.org/email/send.php?mittente=notify@noisepollution.com&destinatario='+email+'&oggetto=ATTENTION:%20maximum%20threshold%20exceeded!&body='+message)
        return HttpResponse()

    if request.method == "GET":
        return HttpResponse(sensor.time_collection)


def add_sensor(request):
    if request.method == "POST":
        form = NewSensor(request.POST)

        if form.is_valid():
            stanza = form.cleaned_data['room']
            if form.cleaned_data['type'] == 'analogical':
                t = True
            else:
                t = False
            key = random_password()

            Sensore.objects.create(room=stanza, type=t, key=key)
            sensor = Sensore.objects.get(key=key)
            print("Sensor "+str(sensor.id)+" create.\n The secure key is "+key+"\nA mail with the infos is coming.")

            if form.cleaned_data['email'] == '':
                email = stanza.mail
            else:
                email = form.cleaned_data['email']
            message = "New sensor with id: "+str(sensor.id)+", has the following security key:\n"+key
            get('http://ame97software.altervista.org/email/send.php?mittente=notify@noisepollution.com&destinatario='+email+'&oggetto=New%20sensor%20added!&body='+message)

            HttpResponse("Sensor "+str(sensor.id)+" create.\n The secure key is "+key+"\nA mail with the infos is coming.")
            return redirect('../manage_sensors/')

    else:
        form = NewSensor()
    return render(request, 'Noise_Pollution/add_sensor.html', {'form': form})


def move_sensor(request, id):
    nome = ''
    if request.method == "POST":
        form = MoveSensor(request.POST)

        if form.is_valid():
            nuova_stanza = form.cleaned_data['room']
            sensor = Sensore.objects.get(id=id)
            sensor.room = nuova_stanza
            nome = nuova_stanza.name
            sensor.save()
            return redirect('../../manage_sensors/')
    else:
        form = MoveSensor()
    return render(request, 'Noise_Pollution/move_sensor.html', {'form': form, 'stanza': nome, 'id': id})


@require_POST
def change_time_collection(request, id):
    try:
        sensor = Sensore.objects.get(id=id)
    except ObjectDoesNotExist:
        print("Sensor "+str(id)+" doesn't exist")
        return HttpResponse("Sensor "+str(id)+" doesn't exist")
    sensor.time_collection = request.POST['time']
    sensor.save()
    HttpResponse("Sensor " + str(id)+" collection time modified")
    return redirect('../../manage_sensors/')

@require_POST
def delete_sensor(request, id):
    try:
        sensor = Sensore.objects.get(id=id)
    except ObjectDoesNotExist:
        print("Sensor "+str(id)+" doesn't exist")
        return HttpResponse("Sensor "+str(id)+" doesn't exist")

    sensor.delete()
    HttpResponse("Sensor "+str(id)+" successfully deleted!")
    return redirect('../../manage_sensors/')


@require_POST
def delete_room(request, id):
    try:
        room = Stanza.objects.get(id=id)
    except ObjectDoesNotExist:

Noise_Pollution/templates/Noise_Pollution/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" type="text/css" href="../../../static/css/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="../../../static/css/font.css">
        <link rel="shortcut icon" href="../../../static/img/favicon.ico" type="image/x-icon">
        <link rel="icon" href="../../../static/img/favicon.ico" type="image/x-icon">
        <link href="../../../static/bootstrap4-glyphicons/css/bootstrap-glyphicons.min.css" rel="stylesheet" type="text/css" />
        <style>
            html, body{ max-height: 100%;}
            body{
                background-color:rgba(20,20,20,1);
            }
            .btn-outline-primary{
                background-color: rgba(0, 123, 239, 0.6);
                color: white;
            }
            .btn-outline-danger{
                background-color: rgba(217,83,79, 0.4);
                color: white;
            }
            .lead{
                font-size: 35px;
            }
            @media screen and (max-width: 600px){
                .display-3 {font-size:3rem !important;}
                .album { padding-top: 0rem !important;}
            }
            @media screen and (max-width: 1005px) and (min-width: 768px){
                .alg1 {padding-top:0 !important;
            }
            @media screen and (max-width: 991px) and (min-width: 768px){
                .alg2 {padding-top:0 !important;
            }
        </style>
        <title>Noise Pollution Detector</title>
    </head>
    <body>
        <div class="text-center p-5 my-3" style="min-height: 4rem;">
            <h1 class="display-3 text-info">Noise Pollution Detector</h1>
        </div>
        <div class="album p-5" style="min-width:100%;">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-4 my-0 pt-2" >
                        <a href="{% url 'Noise_Pollution:sensors' %}" class="btn btn-outline-info" role="button" style="height:220px; width:100%; display: block;"><div class="py-4 my-5 lead">History</div></a>
                    </div>
                    <div class="col-sm-12 col-md-4 pt-2" >
                        <a href="{% url 'Noise_Pollution:rooms' %}" class="btn btn-outline-info" role="button" style="height:220px; width:100%; display: block;"><div class="py-4 my-5 lead alg2">Check Rooms</div></a>
                    </div>
                    <div class="col-sm-12 col-md-4 pt-2">
                        <a href="{% url 'Noise_Pollution:manage_sensors' %}" class="btn btn-outline-info" role="button" style="height:220px; width:100%; display: block;"><div class="py-4 my-5 lead alg1">Manage Sensors</div></a>
                    </div>
                </div>
            </div>
        </div>

        <script src="../../../static/js/jQuery.js"></script>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    </body>
</html>

Noise_Pollution/templates/Noise_Pollution/manage_sensors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" type="text/css" href="../../../static/css/bootstrap.css">
    <link href="../../../static/bootstrap4-glyphicons/css/bootstrap-glyphicons.min.css" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="../../../static/js/jQuery.js"></script>
    <link rel="shortcut icon" href="../../../static/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../../../static/img/favicon.ico" type="image/x-icon">
    <style>
        body{
            background-color:rgba(20,20,20,1);
        }
        #div_id_time{
            margin-top:0.6rem;
        }
        .list-group-item{
            background-color: rgba(255,255,255,0.20);
        }

        .btn-primary, .btn-danger{
            display: none;
        }
        .fade.in {
            opacity: 1;
        }
        .modal.in .modal-dialog {
            -webkit-transform: translate(0, 0);
            -o-transform: translate(0, 0);
            transform: translate(0, 0);
        }
        .modal-backdrop .fade .in {
            opacity: 0.5 !important;
        }
        .modal-backdrop.fade {
            opacity: 0.5 !important;
        }
        @media screen and (max-width: 600px){
            .display-4 {font-size:3rem !important;}
        }
    </style>
    <title>Manage Sensors</title>
</head>
<body>
    <a class="btn btn-outline-info" role="button" href="{% url 'Noise_Pollution:index' %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></a>
    <a class="btn btn-outline-info" role="button" href="{% url 'Noise_Pollution:index' %}" >Home</a>
    <h1 class="display-4 text-info py-2 pl-4">Manage Sensors</h1>
    <hr/><hr/>
    {% if sensori_list %}
        <ul class="list-group col-xl-6 col-lg-8 col-sm-10 col-xs-12 pl-4">
            <div class="row pl-0">
                <p class="text-info col-9 pl-0 mb-0">Sensor:</p>
                <p class="text-info col-3 pl-2 mb-1">Collect Time:</p>
            </div>
        {% for sens in sensori_list %}
            <div class="row">
                <li class="list-group-item col-9">
                    <div class="row" style="max-height:30px;">
                        <div class="row col-11"><p class="text-info p-1">Sensor {{ sens.id  }}: </p>
                            <p class="text-secondary p-1">{% if sens.type %} Analogical{% else %} Digital{% endif %}, {{ sens.room.name }}</p>
                        </div>
                        <div class="col-1 align-middle">
                            <button type="button" class="btn btn-danger py-0 px-1 m-0" data-toggle="modal" data-target="#deleteModal{{sens.id}}">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </button>
                            <a href="{% url 'Noise_Pollution:move_sensor' sens.id %}" role="button" class="btn btn-primary active p-0 m-0" style="min-width:26px;">
                                <span class="glyphicon glyphicon-pencil p-0" aria-hidden="true"></span>
                            </a>
                        </div>
                    </div>
                </li>
                <div class="col-2 p-0 ml-4" style="max-height:30px;">
                    {% load crispy_forms_tags %}
                    {% block content %}
                    <form action="{% url 'Noise_Pollution:change_time_collection' sens.id%}" method="post" id="form{{sens.id}}" class="SetSensorTime row">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <button type="submit" class="col-3 btn btn-outline-info p-0 mt-3 mb-4 ml-2 ">
                            <span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span>
                        </button>
                    </form>
                    {% endblock %}
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="deleteModal{{sens.id}}" tabindex="-1" role="dialog" aria-labelledby="modalTitle{{sens.id}}" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modalTitle{{sens.id}}">Delete Sensor</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                        Are you sure to delete Sensor {{sens.id}}?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                            <form method="post" action="{% url 'Noise_Pollution:delete_sensor' sens.id%}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-info">Yes</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </ul>
    {% else %}
        <p class="text-secondary display-4">No sensors are available.</p>
    {% endif %}
    <hr/>
    <div class="row d-flex justify-content-around p-5">
        <a href="{% url 'Noise_Pollution:add_sensor' %}" role="button" class="btn btn-outline-info col-3">Create</a>
        <button onclick="showDeleteBtn()" class="btn btn-outline-info col-3">Delete</button>
        <button onclick="showMoveBtn()" class="btn btn-outline-info col-3">Move</button>
    </div>
    <script>

        {% for sens in sensori_list %}
        $(function() {
            var x = document.getElementById("form{{sens.id}}").getElementsByClassName("select")[0];
            var c = document.createElement("option");
            var zero = document.createElement("option");
            c.value = {{sens.time_collection}};
            c.text = "{{sens.time_collection}}s";
            zero.value = x.options[x.options.selectedIndex].value;
            zero.text = x.options[0].text;
            if(c.value!=0){
                x.options.add(c,1);
                x.options.remove(0)
                for(i=1; i<x.options.length; i++){
                    if(x.options[i].text == c.text){
                        x.options.remove(i);
                    }
                }
                x.options.add(zero,1);
            }
        })
        {% endfor %}

        function showDeleteBtn(){
            var x=document.getElementsByClassName("btn-primary");
            var i;
            if (x[0].style.display === "block"){
                for (i = 0; i < x.length; i++) {
                    x[i].style.display = "none";
                }
            }

            x=document.getElementsByClassName("btn-danger");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "block";
            }
        };

        function showMoveBtn(){
            var x=document.getElementsByClassName("btn-danger");
            var i;
            if (x[0].style.display === "block"){
                for (i = 0; i < x.length; i++) {
                    x[i].style.display = "none";
                }
            }

            x=document.getElementsByClassName("btn-primary");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "block";
            }
        };

    </script>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
</body>
</html>

Noise_Pollution/templates/Noise_Pollution/rooms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" type="text/css" href="../../../static/css/bootstrap.css">
    <link href="../../../static/bootstrap4-glyphicons/css/bootstrap-glyphicons.min.css" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="../../../static/js/jQuery.js"></script>
    <link rel="shortcut icon" href="../../../static/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../../../static/img/favicon.ico" type="image/x-icon">
    <style>
        body{
            background-color:rgba(20,20,20,1);
        }

        .list-group-item{
            background-color: rgba(255,255,255,0.15);
        }
        .btn-danger{
            display: none;
        }
        .fade.in {
            opacity: 1;
        }
        .modal.in .modal-dialog {
            -webkit-transform: translate(0, 0);
            -o-transform: translate(0, 0);
            transform: translate(0, 0);
        }
        .modal-backdrop .fade .in {
            opacity: 0.5 !important;
        }
        .modal-backdrop.fade {
            opacity: 0.5 !important;
        }
        @media screen and (max-width: 600px){
            .display-4 {font-size:3rem !important;}
        }
    </style>
    <title>Rooms List</title>
</head>
<body>
    <a class="btn btn-outline-info" role="button" href="{% url 'Noise_Pollution:index' %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></a>
    <a class="btn btn-outline-info" role="button" href="{% url 'Noise_Pollution:index' %}" >Home</a>
    <h1 class="display-4 text-info py-2 pl-4">Rooms</h1>
    <hr/><hr/>
    {% if stanza_list %}
        <ul class="list-group col-xl-5 col-lg-8 col-sm-10 col-xs-12 pl-4 ml-3">
            <div class="row">
                <p class="text-info col-9 px-0 mb-0">Room:</p>
                <p class="text-info col-3 pl-4 mb-0">Status:</p>
            </div>
        {% for room in stanza_list %}
            <div class="row align-middle">
                <a href="{% url 'Noise_Pollution:room_sensors' room.id %}" class="list-group-item list-group-item-action col-11">
                    <div class="row" style="max-height:30px;">
                        <div class="row col-11">
                            <p class="text-info p-1">{{room.name}}: </p><p class="text-secondary py-1">{{room.rep}}</p>
                        </div>
                        <div class="col-1">
                            {% for k, v in room_state.items %}
                                {% if k == room.id %}
                                    {% if v == 0 %}
                                        <span class="badge badge-success">Good</span>
                                    {% elif v == 1 %}
                                        <span class="badge badge-danger">Warning</span>
                                    {% elif v == -1 %}
                                        <span class="badge badge-secondary">&nbsp;Idle&nbsp;</span>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </a>
                <div class="col-1 align-middle">
                    <button type="button" class="btn btn-danger py-0 px-1 mt-3" data-toggle="modal" data-target="#deleteModal{{room.id}}">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </button>
                </div>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="deleteModal{{room.id}}" tabindex="-1" role="dialog" aria-labelledby="modalTitle{{room.id}}" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modalTitle{{room.id}}">Delete Sensor</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                        Are you sure to delete {{room.name}}?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                            <form method="post" action="{% url 'Noise_Pollution:delete_room' room.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-info">Yes</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </ul>
    {% else %}
        <p class="text-secondary display-4">No Rooms Added.</p>
    {% endif %}
    <hr/>
    <div class="row d-flex justify-content-around p-5">
        <a href="{% url 'Noise_Pollution:add_room' %}" role="button" class="btn btn-outline-info col-4">Create</a>
        <button onclick="showDeleteBtn()" class="btn btn-outline-info col-4">Delete</button>
    </div>
    <script>
        function showDeleteBtn(){
            var x=document.getElementsByClassName("btn-danger");
            var i;
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "block";
            }
        }

    </script>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
</body>
</html>